name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: deploy
        run: |
          echo "deploying to staging server..."

  # production env is protected - requires 1 approval to deploy
  deployment-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        run: |
          echo "deploying to production server..."
